--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      .
-- Project :      bddProyectoNorte.dm1
-- Author :       juan
--
-- Date Created : Friday, June 12, 2026 23:04:07
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F2_ENS_S1 
--

CREATE TABLE HISTORICO_STATUS_LAPTOP_F2_ENS_S1(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    FECHA_STATUS                  DATE             NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: LAPTOP_F1_ENS_S1 
--

CREATE TABLE LAPTOP_F1_ENS_S1(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)     NOT NULL,
    NOMBRE                    VARCHAR2(100)    NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    RAM_MB                    NUMBER(6, 0)     NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(400)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (LAPTOP_ID)
)
;



-- 
-- TABLE: LAPTOP_INVENTARIO_F2_ENS_S1 
--

CREATE TABLE LAPTOP_INVENTARIO_F2_ENS_S1(
    LAPTOP_ID              NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID    NUMBER(10, 0),
    FECHA_STATUS           DATE             NOT NULL,
    STATUS_LAPTOP_ID       NUMBER(5, 0)     NOT NULL,
    SUCURSAL_ID            NUMBER(10, 0),
    CONSTRAINT PK10 PRIMARY KEY (LAPTOP_ID)
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F1_ENS_S1 
--

CREATE TABLE SERVICIO_LAPTOP_F1_ENS_S1(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    FACTURA         BLOB,
    CONSTRAINT PK12 PRIMARY KEY (NUM_SERVICIO, SUCURSAL_ID)
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(20)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: SUCURSAL_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_F1_ENS_S1(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    ES_VENTA       VARCHAR2(1)      NOT NULL,
    ES_TALLER      VARCHAR2(1)      NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    NOMBRE         VARCHAR2(100)    NOT NULL,
    LATITUD        FLOAT(126)       NOT NULL,
    LONGITUD       FLOAT(126)       NOT NULL,
    URL            VARCHAR2(255)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_TALLER_F1_ENS_S1(
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    TEL_ATENCION    VARCHAR2(10)     NOT NULL,
    DIA_DESCANSO    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_VENTA_F1_ENS_S1(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R 
--

CREATE TABLE TIPO_MONITOR_R(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R 
--

CREATE TABLE TIPO_PROCESADOR_R(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- INDEX: Ref19 
--

CREATE INDEX Ref19 ON HISTORICO_STATUS_LAPTOP_F2_ENS_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: Ref23 
--

CREATE INDEX Ref23 ON LAPTOP_F1_ENS_S1(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref35 
--

CREATE INDEX Ref35 ON LAPTOP_F1_ENS_S1(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref46 
--

CREATE INDEX Ref46 ON LAPTOP_F1_ENS_S1(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref57 
--

CREATE INDEX Ref57 ON LAPTOP_F1_ENS_S1(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref61 
--

CREATE INDEX Ref61 ON LAPTOP_INVENTARIO_F2_ENS_S1(SUCURSAL_ID)
;
-- 
-- INDEX: Ref18 
--

CREATE INDEX Ref18 ON LAPTOP_INVENTARIO_F2_ENS_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: Ref810 
--

CREATE INDEX Ref810 ON SERVICIO_LAPTOP_F1_ENS_S1(SUCURSAL_ID)
;
-- 
-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F2_ENS_S1 
--

ALTER TABLE HISTORICO_STATUS_LAPTOP_F2_ENS_S1 ADD CONSTRAINT RefSTATUS_LAPTOP9 
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)  DEFERRABLE
;


-- 
-- TABLE: LAPTOP_F1_ENS_S1 
--

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT RefTIPO_PROCESADOR_R3 
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R(TIPO_PROCESADOR_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT RefTIPO_TARJETA_VIDEO_R5 
    FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R(TIPO_TARJETA_VIDEO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT RefTIPO_ALMACENAMIENTO_R6 
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R(TIPO_ALMACENAMIENTO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT RefTIPO_MONITOR_R7 
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R(TIPO_MONITOR_ID)  DEFERRABLE
;


-- 
-- TABLE: LAPTOP_INVENTARIO_F2_ENS_S1 
--

ALTER TABLE LAPTOP_INVENTARIO_F2_ENS_S1 ADD CONSTRAINT RefSUCURSAL_F1_ENS_S11 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_ENS_S1(SUCURSAL_ID)
;

ALTER TABLE LAPTOP_INVENTARIO_F2_ENS_S1 ADD CONSTRAINT RefSTATUS_LAPTOP8 
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)  DEFERRABLE
;


-- 
-- TABLE: SERVICIO_LAPTOP_F1_ENS_S1 
--

ALTER TABLE SERVICIO_LAPTOP_F1_ENS_S1 ADD CONSTRAINT RefSUCURSAL_TALLER_F1_ENS_S110 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F1_ENS_S1(SUCURSAL_ID)  DEFERRABLE
;


-- 
-- TABLE: SUCURSAL_TALLER_F1_ENS_S1 
--

ALTER TABLE SUCURSAL_TALLER_F1_ENS_S1 ADD CONSTRAINT RefSUCURSAL_F1_ENS_S12 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_ENS_S1(SUCURSAL_ID)
;


-- 
-- TABLE: SUCURSAL_VENTA_F1_ENS_S1 
--

ALTER TABLE SUCURSAL_VENTA_F1_ENS_S1 ADD CONSTRAINT RefSUCURSAL_F1_ENS_S14 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_ENS_S1(SUCURSAL_ID)
;


