--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      .
-- Project :      bddProyectoEste.dm1
-- Author :       juan
--
-- Date Created : Friday, June 12, 2026 22:55:27
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F1_ENS_S2 
--

CREATE TABLE HISTORICO_STATUS_LAPTOP_F1_ENS_S2(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    FECHA_STATUS                  DATE             NOT NULL
)
;



-- 
-- TABLE: LAPTOP_F4_ENS_S2 
--

CREATE TABLE LAPTOP_F4_ENS_S2(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0)    NOT NULL,
    NUM_SERIE                 VARCHAR2(18)     NOT NULL,
    NOMBRE                    VARCHAR2(100)    NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    RAM_MB                    NUMBER(6, 0)     NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(400)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F2_ENS_S2 
--

CREATE TABLE SERVICIO_LAPTOP_F2_ENS_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    FACTURA         BLOB
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(20)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_F2_ENS_S2 
--

CREATE TABLE SUCURSAL_F2_ENS_S2(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    ES_TALLER      VARCHAR2(1)      NOT NULL,
    ES_VENTA       VARCHAR2(1)      NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    NOMBRE         VARCHAR2(100)    NOT NULL,
    LATITUD        FLOAT(126)       NOT NULL,
    LONGITUD       FLOAT(126)       NOT NULL,
    URL            VARCHAR2(255)    NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F2_ENS_S2 
--

CREATE TABLE SUCURSAL_TALLER_F2_ENS_S2(
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    TEL_ATENCION    VARCHAR2(10)     NOT NULL,
    DIA_DESCANSO    NUMBER(1, 0)     NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F2_ENS_S2 
--

CREATE TABLE SUCURSAL_VENTA_F2_ENS_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_MONITOR_R 
--

CREATE TABLE TIPO_MONITOR_R(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R 
--

CREATE TABLE TIPO_PROCESADOR_R(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL
)
;



-- 
-- INDEX: Ref17 
--

CREATE INDEX Ref17 ON HISTORICO_STATUS_LAPTOP_F1_ENS_S2(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: Ref23 
--

CREATE INDEX Ref23 ON LAPTOP_F4_ENS_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref34 
--

CREATE INDEX Ref34 ON LAPTOP_F4_ENS_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref45 
--

CREATE INDEX Ref45 ON LAPTOP_F4_ENS_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref56 
--

CREATE INDEX Ref56 ON LAPTOP_F4_ENS_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref88 
--

CREATE INDEX Ref88 ON SERVICIO_LAPTOP_F2_ENS_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref61 
--


ALTER TABLE HISTORICO_STATUS_LAPTOP_F1_ENS_S2 ADD 
    CONSTRAINT PK22 PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID)
;

-- 
-- TABLE: LAPTOP_F4_ENS_S2 
--

ALTER TABLE LAPTOP_F4_ENS_S2 ADD 
    CONSTRAINT PK21 PRIMARY KEY (LAPTOP_ID)
;

-- 
-- TABLE: SERVICIO_LAPTOP_F2_ENS_S2 
--

ALTER TABLE SERVICIO_LAPTOP_F2_ENS_S2 ADD 
    CONSTRAINT PK23 PRIMARY KEY (NUM_SERVICIO, SUCURSAL_ID)
;

-- 
-- TABLE: STATUS_LAPTOP 
--

ALTER TABLE STATUS_LAPTOP ADD 
    CONSTRAINT PK13 PRIMARY KEY (STATUS_LAPTOP_ID)
;

-- 
-- TABLE: SUCURSAL_F2_ENS_S2 
--

ALTER TABLE SUCURSAL_F2_ENS_S2 ADD 
    CONSTRAINT PK18 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: SUCURSAL_TALLER_F2_ENS_S2 
--

ALTER TABLE SUCURSAL_TALLER_F2_ENS_S2 ADD 
    CONSTRAINT PK20 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: SUCURSAL_VENTA_F2_ENS_S2 
--

ALTER TABLE SUCURSAL_VENTA_F2_ENS_S2 ADD 
    CONSTRAINT PK19 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

ALTER TABLE TIPO_ALMACENAMIENTO_R ADD 
    CONSTRAINT PK16 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
;

-- 
-- TABLE: TIPO_MONITOR_R 
--

ALTER TABLE TIPO_MONITOR_R ADD 
    CONSTRAINT PK17 PRIMARY KEY (TIPO_MONITOR_ID)
;

-- 
-- TABLE: TIPO_PROCESADOR_R 
--

ALTER TABLE TIPO_PROCESADOR_R ADD 
    CONSTRAINT PK14 PRIMARY KEY (TIPO_PROCESADOR_ID)
;

-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

ALTER TABLE TIPO_TARJETA_VIDEO_R ADD 
    CONSTRAINT PK15 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
;

-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F1_ENS_S2 
--

ALTER TABLE HISTORICO_STATUS_LAPTOP_F1_ENS_S2 ADD CONSTRAINT RefSTATUS_LAPTOP7 
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)  DEFERRABLE
;


-- 
-- TABLE: LAPTOP_F4_ENS_S2 
--

ALTER TABLE LAPTOP_F4_ENS_S2 ADD CONSTRAINT RefTIPO_PROCESADOR_R3 
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R(TIPO_PROCESADOR_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F4_ENS_S2 ADD CONSTRAINT RefTIPO_TARJETA_VIDEO_R4 
    FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R(TIPO_TARJETA_VIDEO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F4_ENS_S2 ADD CONSTRAINT RefTIPO_ALMACENAMIENTO_R5 
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R(TIPO_ALMACENAMIENTO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F4_ENS_S2 ADD CONSTRAINT RefTIPO_MONITOR_R6 
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R(TIPO_MONITOR_ID)  DEFERRABLE
;


-- 
-- TABLE: SERVICIO_LAPTOP_F2_ENS_S2 
--

ALTER TABLE SERVICIO_LAPTOP_F2_ENS_S2 ADD CONSTRAINT RefSUCURSAL_TALLER_F2_ENS_S28 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F2_ENS_S2(SUCURSAL_ID)  DEFERRABLE
;


-- 
-- TABLE: SUCURSAL_TALLER_F2_ENS_S2 
--

ALTER TABLE SUCURSAL_TALLER_F2_ENS_S2 ADD CONSTRAINT RefSUCURSAL_F2_ENS_S21 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_ENS_S2(SUCURSAL_ID)
;


-- 
-- TABLE: SUCURSAL_VENTA_F2_ENS_S2 
--

ALTER TABLE SUCURSAL_VENTA_F2_ENS_S2 ADD CONSTRAINT RefSUCURSAL_F2_ENS_S22 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_ENS_S2(SUCURSAL_ID)
;


