--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      .
-- Project :      bddProyectoSur.dm1
-- Author :       juan
--
-- Date Created : Friday, June 12, 2026 23:19:00
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: LAPTOP_F2_AAD_S2 
--

CREATE TABLE LAPTOP_F2_AAD_S2(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REPUESTO_ID        NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)     NOT NULL,
    NOMBRE                    VARCHAR2(100)    NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    RAM_MB                    NUMBER(6, 0)     NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(400)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL
)
;



-- 
-- TABLE: LAPTOP_F5_AAD_S2 
--

CREATE TABLE LAPTOP_F5_AAD_S2(
    LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    FOTO         BLOB             NOT NULL
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F4_AAD_S2 
--

CREATE TABLE SERVICIO_LAPTOP_F4_AAD_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    FACTURA         BLOB
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(20)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_F4_AAD_S2 
--

CREATE TABLE SUCURSAL_F4_AAD_S2(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    ES_TALLER      VARCHAR2(1)      NOT NULL,
    ES_VENTA       VARCHAR2(40)     NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    NOMBRE         VARCHAR2(100)    NOT NULL,
    LATITUD        FLOAT(126)       NOT NULL,
    LONGITUD       FLOAT(126)       NOT NULL,
    URL            VARCHAR2(255)    NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F4_AAD_S2 
--

CREATE TABLE SUCURSAL_TALLER_F4_AAD_S2(
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    TEL_ATENCION    VARCHAR2(10)     NOT NULL,
    DIA_DESCANSO    NUMBER(1, 0)     NOT NULL
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F4_AAD_S2 
--

CREATE TABLE SUCURSAL_VENTA_F4_AAD_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_MONITOR_R 
--

CREATE TABLE TIPO_MONITOR_R(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R 
--

CREATE TABLE TIPO_PROCESADOR_R(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL
)
;



-- 
-- INDEX: Ref11 
--

CREATE INDEX Ref11 ON LAPTOP_F2_AAD_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref22 
--

CREATE INDEX Ref22 ON LAPTOP_F2_AAD_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref33 
--

CREATE INDEX Ref33 ON LAPTOP_F2_AAD_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref44 
--

CREATE INDEX Ref44 ON LAPTOP_F2_AAD_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref75 
--

CREATE INDEX Ref75 ON SERVICIO_LAPTOP_F4_AAD_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref98 
--

CREATE INDEX Ref98 ON SERVICIO_LAPTOP_F4_AAD_S2(LAPTOP_ID)
;
-- 
-- INDEX: Ref56 
--

CREATE INDEX Ref56 ON SUCURSAL_TALLER_F4_AAD_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref57 
--

CREATE INDEX Ref57 ON SUCURSAL_VENTA_F4_AAD_S2(SUCURSAL_ID)
;
-- 
-- TABLE: LAPTOP_F2_AAD_S2 
--

ALTER TABLE LAPTOP_F2_AAD_S2 ADD 
    CONSTRAINT PK43 PRIMARY KEY (LAPTOP_ID)
;

-- 
-- TABLE: LAPTOP_F5_AAD_S2 
--

ALTER TABLE LAPTOP_F5_AAD_S2 ADD 
    CONSTRAINT PK44 PRIMARY KEY (LAPTOP_ID)
;

-- 
-- TABLE: SERVICIO_LAPTOP_F4_AAD_S2 
--

ALTER TABLE SERVICIO_LAPTOP_F4_AAD_S2 ADD 
    CONSTRAINT PK45 PRIMARY KEY (NUM_SERVICIO, SUCURSAL_ID)
;

-- 
-- TABLE: STATUS_LAPTOP 
--

ALTER TABLE STATUS_LAPTOP ADD 
    CONSTRAINT PK24 PRIMARY KEY (STATUS_LAPTOP_ID)
;

-- 
-- TABLE: SUCURSAL_F4_AAD_S2 
--

ALTER TABLE SUCURSAL_F4_AAD_S2 ADD 
    CONSTRAINT PK40 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: SUCURSAL_TALLER_F4_AAD_S2 
--

ALTER TABLE SUCURSAL_TALLER_F4_AAD_S2 ADD 
    CONSTRAINT PK42 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: SUCURSAL_VENTA_F4_AAD_S2 
--

ALTER TABLE SUCURSAL_VENTA_F4_AAD_S2 ADD 
    CONSTRAINT PK41 PRIMARY KEY (SUCURSAL_ID)
;

-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

ALTER TABLE TIPO_ALMACENAMIENTO_R ADD 
    CONSTRAINT PK38 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
;

-- 
-- TABLE: TIPO_MONITOR_R 
--

ALTER TABLE TIPO_MONITOR_R ADD 
    CONSTRAINT PK39 PRIMARY KEY (TIPO_MONITOR_ID)
;

-- 
-- TABLE: TIPO_PROCESADOR_R 
--

ALTER TABLE TIPO_PROCESADOR_R ADD 
    CONSTRAINT PK36 PRIMARY KEY (TIPO_PROCESADOR_ID)
;

-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

ALTER TABLE TIPO_TARJETA_VIDEO_R ADD 
    CONSTRAINT PK37 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
;

-- 
-- TABLE: LAPTOP_F2_AAD_S2 
--

ALTER TABLE LAPTOP_F2_AAD_S2 ADD CONSTRAINT RefTIPO_PROCESADOR_R1 
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R(TIPO_PROCESADOR_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F2_AAD_S2 ADD CONSTRAINT RefTIPO_TARJETA_VIDEO_R2 
    FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R(TIPO_TARJETA_VIDEO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F2_AAD_S2 ADD CONSTRAINT RefTIPO_ALMACENAMIENTO_R3 
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R(TIPO_ALMACENAMIENTO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F2_AAD_S2 ADD CONSTRAINT RefTIPO_MONITOR_R4 
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R(TIPO_MONITOR_ID)  DEFERRABLE
;


-- 
-- TABLE: SERVICIO_LAPTOP_F4_AAD_S2 
--

ALTER TABLE SERVICIO_LAPTOP_F4_AAD_S2 ADD CONSTRAINT RefSUCURSAL_TALLER_F4_AAD_S25 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F4_AAD_S2(SUCURSAL_ID)  DEFERRABLE
;

ALTER TABLE SERVICIO_LAPTOP_F4_AAD_S2 ADD CONSTRAINT RefLAPTOP_F5_AAD_S28 
    FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_F5_AAD_S2(LAPTOP_ID)
;


-- 
-- TABLE: SUCURSAL_TALLER_F4_AAD_S2 
--

ALTER TABLE SUCURSAL_TALLER_F4_AAD_S2 ADD CONSTRAINT RefSUCURSAL_F4_AAD_S26 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_AAD_S2(SUCURSAL_ID)
;


-- 
-- TABLE: SUCURSAL_VENTA_F4_AAD_S2 
--

ALTER TABLE SUCURSAL_VENTA_F4_AAD_S2 ADD CONSTRAINT RefSUCURSAL_F4_AAD_S27 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_AAD_S2(SUCURSAL_ID)
;


