--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      .
-- Project :      bddProyectoNorte.dm1
-- Author :       juan
--
-- Date Created : Friday, June 12, 2026 23:04:07
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F2_ENS_S1 
--

CREATE TABLE HISTORICO_STATUS_LAPTOP_F2_ENS_S1(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    FECHA_STATUS                  DATE             NOT NULL,
    CONSTRAINT HISTORICO_STATUS_LAPTOP_F2_ENS_S1_pk PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: LAPTOP_F1_ENS_S1 
--

CREATE TABLE LAPTOP_F1_ENS_S1(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)     NOT NULL,
    CANTIDAD_RAM                  NUMBER(6, 0)     NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL,
    CONSTRAINT LAPTOP_F1_ENS_S1_pk PRIMARY KEY (LAPTOP_ID)
)
;



-- 
-- TABLE: LAPTOP_INVENTARIO_F2_ENS_S1 
--

CREATE TABLE LAPTOP_INVENTARIO_F2_ENS_S1(
    LAPTOP_ID              NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID    NUMBER(10, 0),
    FECHA_STATUS           DATE             NOT NULL,
    STATUS_LAPTOP_ID       NUMBER(5, 0)     NOT NULL,
    SUCURSAL_ID            NUMBER(10, 0),
    CONSTRAINT LAPTOP_INVENTARIO_F2_ENS_S1_pk PRIMARY KEY (LAPTOP_ID)
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F1_ENS_S1 
--

CREATE TABLE SERVICIO_LAPTOP_F1_ENS_S1(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    FACTURA         BLOB,
    CONSTRAINT SERVICIO_LAPTOP_F1_ENS_S1_pk PRIMARY KEY (num_servicio, laptop_id)
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(20)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT STATUS_LAPTOP_pk PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: SUCURSAL_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_F1_ENS_S1(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    ES_VENTA       VARCHAR2(1)      NOT NULL,
    ES_TALLER      VARCHAR2(1)      NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    NOMBRE         VARCHAR2(100)    NOT NULL,
    LATITUD        FLOAT(126)       NOT NULL,
    LONGITUD       FLOAT(126)       NOT NULL,
    URL            VARCHAR2(255)    NOT NULL,
    CONSTRAINT SUCURSAL_F1_ENS_S1_pk PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_TALLER_F1_ENS_S1(
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    telefono_atencion    VARCHAR2(20)     NOT NULL,
    DIA_DESCANSO    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT SUCURSAL_TALLER_F1_ENS_S1_pk PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F1_ENS_S1 
--

CREATE TABLE SUCURSAL_VENTA_F1_ENS_S1(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT SUCURSAL_VENTA_F1_ENS_S1_pk PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_ALMACENAMIENTO_R_pk PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R 
--

CREATE TABLE TIPO_MONITOR_R(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_MONITOR_R_pk PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R 
--

CREATE TABLE TIPO_PROCESADOR_R(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_PROCESADOR_R_pk PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_TARJETA_VIDEO_R_pk PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- INDEX: HISTORICO_STATUS_LAPTOP_F2_ENS_S1_STATUS_LAPTOP_ID_iux 
--

CREATE INDEX HISTORICO_STATUS_LAPTOP_F2_ENS_S1_STATUS_LAPTOP_ID_iux ON HISTORICO_STATUS_LAPTOP_F2_ENS_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: LAPTOP_F1_ENS_S1_TIPO_PROCESADOR_ID_iux 
--

CREATE INDEX LAPTOP_F1_ENS_S1_TIPO_PROCESADOR_ID_iux ON LAPTOP_F1_ENS_S1(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: LAPTOP_F1_ENS_S1_TIPO_TARJETA_VIDEO_ID_iux 
--

CREATE INDEX LAPTOP_F1_ENS_S1_TIPO_TARJETA_VIDEO_ID_iux ON LAPTOP_F1_ENS_S1(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: LAPTOP_F1_ENS_S1_TIPO_ALMACENAMIENTO_ID_iux 
--

CREATE INDEX LAPTOP_F1_ENS_S1_TIPO_ALMACENAMIENTO_ID_iux ON LAPTOP_F1_ENS_S1(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: LAPTOP_F1_ENS_S1_TIPO_MONITOR_ID_iux 
--

CREATE INDEX LAPTOP_F1_ENS_S1_TIPO_MONITOR_ID_iux ON LAPTOP_F1_ENS_S1(TIPO_MONITOR_ID)
;
-- 
-- INDEX: LAPTOP_INVENTARIO_F2_ENS_S1_SUCURSAL_ID_iux 
--

CREATE INDEX LAPTOP_INVENTARIO_F2_ENS_S1_SUCURSAL_ID_iux ON LAPTOP_INVENTARIO_F2_ENS_S1(SUCURSAL_ID)
;
-- 
-- INDEX: LAPTOP_INVENTARIO_F2_ENS_S1_STATUS_LAPTOP_ID_iux 
--

CREATE INDEX LAPTOP_INVENTARIO_F2_ENS_S1_STATUS_LAPTOP_ID_iux ON LAPTOP_INVENTARIO_F2_ENS_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: SERVICIO_LAPTOP_F1_ENS_S1_SUCURSAL_ID_iux 
--

CREATE INDEX SERVICIO_LAPTOP_F1_ENS_S1_SUCURSAL_ID_iux ON SERVICIO_LAPTOP_F1_ENS_S1(SUCURSAL_ID)
;
-- 
-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F2_ENS_S1 
--

ALTER TABLE HISTORICO_STATUS_LAPTOP_F2_ENS_S1 ADD CONSTRAINT HISTORICO_STATUS_LAPTOP_F2_ENS_S1_STATUS_LAPTOP_ID_fk 
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)  DEFERRABLE
;


-- 
-- TABLE: LAPTOP_F1_ENS_S1 
--

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT LAPTOP_F1_ENS_S1_TIPO_PROCESADOR_ID_fk 
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R(TIPO_PROCESADOR_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT LAPTOP_F1_ENS_S1_TIPO_TARJETA_VIDEO_ID_fk 
    FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R(TIPO_TARJETA_VIDEO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT LAPTOP_F1_ENS_S1_TIPO_ALMACENAMIENTO_ID_fk 
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R(TIPO_ALMACENAMIENTO_ID)  DEFERRABLE
;

ALTER TABLE LAPTOP_F1_ENS_S1 ADD CONSTRAINT LAPTOP_F1_ENS_S1_TIPO_MONITOR_ID_fk 
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R(TIPO_MONITOR_ID)  DEFERRABLE
;


-- 
-- TABLE: LAPTOP_INVENTARIO_F2_ENS_S1 
--



ALTER TABLE LAPTOP_INVENTARIO_F2_ENS_S1 ADD CONSTRAINT LAPTOP_INVENTARIO_F2_ENS_S1_STATUS_LAPTOP_ID_fk 
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)  DEFERRABLE
;


-- 
-- TABLE: SERVICIO_LAPTOP_F1_ENS_S1 
--

ALTER TABLE SERVICIO_LAPTOP_F1_ENS_S1 ADD CONSTRAINT SERVICIO_LAPTOP_F1_ENS_S1_SUCURSAL_ID_fk 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F1_ENS_S1(SUCURSAL_ID)  DEFERRABLE
;


-- 
-- TABLE: SUCURSAL_TALLER_F1_ENS_S1 
--

ALTER TABLE SUCURSAL_TALLER_F1_ENS_S1 ADD CONSTRAINT SUCURSAL_TALLER_F1_ENS_S1_SUCURSAL_ID_fk 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_ENS_S1(SUCURSAL_ID)
;


-- 
-- TABLE: SUCURSAL_VENTA_F1_ENS_S1 
--

ALTER TABLE SUCURSAL_VENTA_F1_ENS_S1 ADD CONSTRAINT SUCURSAL_VENTA_F1_ENS_S1_SUCURSAL_ID_fk 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_ENS_S1(SUCURSAL_ID)
;